storage_name         = "ap-resume"
tfstate_storage_name = "ap-tfstate"
location             = "US"
project_id           = "psyched-age-416001"
tfstate_project_id   = "infra-419705"
region_id            = "us-west1"
zone_id              = "us-west1-b"