storage_name         = "ap-resume-bucket"
tfstate_storage_name = "ap-tfstate-bucket"
location             = "US"
project_id           = "psyched-age-416001"
region_id            = "us-west1"
zone_id              = "us-west1-b"