storage_name         = "stg_resume_bucket"
tfstate_storage_name = "stg_tfstate_bucket"
location             = "US"
project_id           = "psyched-age-416001"
region_id            = "us-west1"
zone_id              = "us-west1-b"