gcloud functions deploy add-visitor-count \
--project=projectname \
--region=us-west1 \
--runtime=python312 \
--source=sourcepath \
--entry-point=entryfunction \
--trigger-http \
--no-allow-unauthenticated \
--gen2 \
--memory=128Mi \
--cpu=83m