name: Upload files to GCS bucket

on:
  push:
    branches: [develop]

jobs:
  upload_to_bucket:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - id: "checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/88827294723/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "sa-github@psyched-age-416001.iam.gserviceaccount.com"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "web"
          destination: "dev_resume_bucket"
          parent: false
