name: Provision GCP storage website infra

on:
  push:
    branches: [main]

jobs:
  terraform:
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write" # Needed to comment on the PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: "projects/88827294723/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "sa-github@psyched-age-416001.iam.gserviceaccount.com"

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - id: fmt
        name: Terraform fmt
        working-directory: config
        run: terraform fmt -check

      - id: init
        name: Terraform Init
        working-directory: config
        run: terraform init

      - id: validate
        name: Terraform Validate
        run: terraform validate -no-color

      - id: plan
        name: Terrform Plan
        working-directory: config
        run: terraform plan -no-color
