name: Provision GCP storage website infra

on:
  push:
    branches: [main]

jobs:
  terraform:
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write" # Needed to comment on the PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.INFRA_WIP }}
          service_account: ${{ secrets.INFRA_SERVICE_ACCOUNT }}

      - uses: hashicorp/setup-terraform@main
        with:
          terraform_version: 1.4.0

      - id: fmt
        name: Terraform fmt
        working-directory: config
        run: terraform fmt -check

      - id: init
        name: Terraform Init
        working-directory: config
        run: terraform init

      - id: validate
        name: Terraform Validate
        run: terraform validate -no-color

      - id: plan
        name: Terrform Plan
        working-directory: config
        run: terraform plan -var-file="resume.tfvars" -no-color

      - id: apply
        name: Terraform Apply
        working-directory: config
        run: terraform apply -var-file="resume.tfvars" -auto-approve -destroy
