name: Upload files to GCS bucket

on:
  push:
    branches: [main]

jobs:
  upload_to_bucket:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - id: "checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.RESUME_WIP }}
          service_account: ${{ secrets.RESUME_SERVICE_ACCOUNT }}

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "web"
          destination: ap-resume
          parent: false
